### PR TITLE
Added second session to webpage

### PR DESCRIPTION
**Pull request by Fir121**
Uncommented the second session. So that it will appear on the website.

### CODE REVIEW

**Comment by Fir121** [comment]
Squash and merge preferably. Fixed an issue with Safari table rendering, thanks @Sanvit-Katrekar for the help

**Comment by Fir121** [comment]
[Preview Here](https://fir121.github.io/ml-bootcamp-2023/)

**Review by abxhr — CHANGES_REQUESTED** [review]
Dope work! 🚀
Few additions before we could merge it in:
- In the `Model Building I` page, I can't see the other topics mentioned in the `Table of Contents` (right), from the topic `Linear Regression`. Could you give that a look? (*I guess its a formatting issue)
- Could you also add in the contributors to the index page (and the `README.md` of the repo)? Why is only my name there ☠

**Comment by Fir121** [comment]
Done :thumbsup:

**Pull request merged**
